## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split
X_0, y_0 = X[y==0], y[y==0]
X_1, y_1 = X[y==1], y[y==1]

In [4]:
X_train_0, X_test_0, y_train_0, y_test_0 = train_test_split(X_0, y_0, test_size=10/len(y_0), random_state=42)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=10/len(y_1), random_state=42)

In [5]:
X_train = np.concatenate((X_train_0, X_train_1), axis=None)
X_train

array([295, 296, 297, 298, 299, 620, 621, 622, 623, 624, 275, 276, 277,
       278, 279, 530, 531, 532, 533, 534, 320, 321, 322, 323, 324, 350,
       351, 352, 353, 354, 840, 841, 842, 843, 844, 935, 936, 937, 938,
       939, 690, 691, 692, 693, 694, 280, 281, 282, 283, 284, 575, 576,
       577, 578, 579, 290, 291, 292, 293, 294, 260, 261, 262, 263, 264,
       245, 246, 247, 248, 249, 355, 356, 357, 358, 359, 955, 956, 957,
       958, 959, 685, 686, 687, 688, 689, 480, 481, 482, 483, 484, 855,
       856, 857, 858, 859, 720, 721, 722, 723, 724, 880, 881, 882, 883,
       884, 590, 591, 592, 593, 594, 500, 501, 502, 503, 504, 775, 776,
       777, 778, 779, 210, 211, 212, 213, 214, 815, 816, 817, 818, 819,
       425, 426, 427, 428, 429, 410, 411, 412, 413, 414, 545, 546, 547,
       548, 549, 650, 651, 652, 653, 654, 330, 331, 332, 333, 334, 890,
       891, 892, 893, 894, 610, 611, 612, 613, 614, 680, 681, 682, 683,
       684, 930, 931, 932, 933, 934, 380, 381, 382, 383, 384, 60

In [6]:
y_train = np.concatenate((y_train_0, y_train_1), axis=None)
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
X_test = np.concatenate((X_test_0, X_test_1), axis=None)
X_test

array([725, 726, 727, 728, 729, 740, 741, 742, 743, 744, 905, 906, 907,
       908, 909, 475, 476, 477, 478, 479, 670, 671, 672, 673, 674, 345,
       346, 347, 348, 349, 705, 706, 707, 708, 709, 455, 456, 457, 458,
       459, 700, 701, 702, 703, 704, 910, 911, 912, 913, 914,  95,  96,
        97,  98,  99,  80,  81,  82,  83,  84,  75,  76,  77,  78,  79,
       130, 131, 132, 133, 134,  20,  21,  22,  23,  24,  60,  61,  62,
        63,  64, 185, 186, 187, 188, 189, 135, 136, 137, 138, 139, 195,
       196, 197, 198, 199,  30,  31,  32,  33,  34])

In [8]:
y_test = np.concatenate((y_test_0, y_test_1), axis=None)
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])